-- Create custom types
CREATE TYPE user_role AS ENUM ('employee', 'hod');
CREATE TYPE report_status AS ENUM ('draft', 'submitted', 'approved', 'rejected', 'modification_requested');

-- Create profiles table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  employee_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role user_role DEFAULT 'employee'::user_role NOT NULL,
  department TEXT NOT NULL,
  designation TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Create daily_reports table
CREATE TABLE daily_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID REFERENCES profiles(id) NOT NULL,
  report_date DATE NOT NULL,
  task_name TEXT NOT NULL,
  work_description TEXT NOT NULL,
  hours_worked NUMERIC(4,2) NOT NULL,
  challenges_faced TEXT,
  completion_percentage INTEGER NOT NULL,
  evidence_url TEXT,
  status report_status DEFAULT 'draft'::report_status NOT NULL,
  hod_comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ
);

-- Setup Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_reports ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone." ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Daily Reports Policies
CREATE POLICY "Employees can view their own reports" ON daily_reports
  FOR SELECT USING (auth.uid() = employee_id);

CREATE POLICY "HODs can view all reports in their department" ON daily_reports
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
    )
  );

CREATE POLICY "Employees can create their own reports" ON daily_reports
  FOR INSERT WITH CHECK (auth.uid() = employee_id);

CREATE POLICY "Employees can update their own draft/rejected reports" ON daily_reports
  FOR UPDATE USING (
    auth.uid() = employee_id 
    AND status IN ('draft', 'rejected', 'modification_requested')
  );

CREATE POLICY "HODs can update report status" ON daily_reports
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role = 'hod'
    )
  );

-- Create trigger to automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, employee_id, name, email, department, designation, role)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'employee_id', 'EMP' || floor(random() * 10000)::text),
    COALESCE(new.raw_user_meta_data->>'name', 'New Employee'),
    new.email,
    COALESCE(new.raw_user_meta_data->>'department', 'Engineering'),
    COALESCE(new.raw_user_meta_data->>'designation', 'Software Engineer'),
    COALESCE((new.raw_user_meta_data->>'role')::user_role, 'employee'::user_role)
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
